training with ppo
INFO:2025-07-06 23:01:06,250:jax._src.xla_bridge:752: Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
[2025-07-06 23:01:06,250][jax._src.xla_bridge][INFO] - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
[2025-07-06 23:01:06,910][root][INFO] - Using JAX default device: cuda:0.
[2025-07-06 23:01:06,911][root][INFO] - MJX Warp is disabled via MJX_WARP_ENABLED=false.
[2025-07-06 23:01:08,437][absl][INFO] - Device count: 1, process count: 1 (id 0), local device count: 1, devices to be used count: 1
[2025-07-06 23:01:31,551][root][INFO] - Using JAX default device: cuda:0.
[2025-07-06 23:01:31,552][root][INFO] - MJX Warp is disabled via MJX_WARP_ENABLED=false.
[2025-07-06 23:02:39,402][root][INFO] - Using JAX default device: cuda:0.
[2025-07-06 23:02:39,402][root][INFO] - MJX Warp is disabled via MJX_WARP_ENABLED=false.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/wandb/sdk/lib/exit_hooks.py", line 52, in exc_handler
    traceback.print_exception(exc_type, exc, tb)
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/traceback.py", line 124, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/traceback.py", line 733, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/traceback.py", line 438, in _extract_from_extended_frame_gen
    f.line
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/traceback.py", line 323, in line
    self._line = linecache.getline(self.filename, self.lineno)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/linecache.py", line 142, in updatecache
    lines = fp.readlines()
            ^^^^^^^^^^^^^^
  File "<frozen codecs>", line 319, in decode
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/interpreters/pxla.py", line 2743, in _cached_compilation
    xla_executable = compiler.compile_or_get_cached(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/compiler.py", line 500, in compile_or_get_cached
    return _compile_and_write_cache(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/compiler.py", line 768, in _compile_and_write_cache
    executable = backend_compile_and_load(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/profiler.py", line 354, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/compiler.py", line 395, in backend_compile_and_load
    raise e
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/compiler.py", line 385, in backend_compile_and_load
    return backend.compile_and_load(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib._jax.XlaRuntimeError: INTERNAL: ptxas exited with non-zero error code 2, output:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ros/mujoco_playground/learning/train.py", line 213, in <module>
    if __name__ == "__main__":
        ^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
          ^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/mujoco_playground/learning/train.py", line 202, in train
    elif cfg.policy == "ppo":

  File "/home/ros/mujoco_playground/learning/train.py", line 126, in train_ppo
    make_inference_fn, params, metrics = train_fn(
                                         ^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/brax/training/agents/ppo/train.py", line 675, in train
    metrics = evaluator.run_evaluation(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/brax/training/acting.py", line 133, in run_evaluation
    eval_state = self._generate_eval_unroll(policy_params, unroll_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/traceback_util.py", line 182, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/pjit.py", line 292, in cache_miss
    executable, pgle_profiler) = _python_pjit_helper(fun, jit_info, *args, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/pjit.py", line 153, in _python_pjit_helper
    out_flat, compiled, profiler = _pjit_call_impl_python(*args_flat, **p.params)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/pjit.py", line 1855, in _pjit_call_impl_python
    ).compile()
      ^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/interpreters/pxla.py", line 2410, in compile
    executable = UnloadedMeshExecutable.from_hlo(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/interpreters/pxla.py", line 2952, in from_hlo
    xla_executable = _cached_compilation(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/interpreters/pxla.py", line 2740, in _cached_compilation
    with dispatch.log_elapsed_time(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/dispatch.py", line 190, in __exit__
    def __exit__(self, exc_type, exc_value, traceback):

KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x7bdee0e5f740>
Traceback (most recent call last):
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/wandb/sdk/lib/service/service_connection.py", line 54, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/wandb/sdk/lib/service/service_connection.py", line 182, in teardown
    self._router.join()
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/threading.py", line 1149, in join
    self._wait_for_tstate_lock()
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/threading.py", line 1169, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
Exception ignored in atexit callback: <function clean_up at 0x7bdf0b8c62a0>
Traceback (most recent call last):
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/api.py", line 3188, in clean_up
    clear_backends()
  File "/home/ros/miniconda3/envs/mujoco/lib/python3.12/site-packages/jax/_src/api.py", line 3181, in clear_backends
    pjit._cpp_pjit_cache_explicit_attributes.clear()
KeyboardInterrupt:
